name: CI/CD Pipeline
'on':
  push:
    branches:
    - main
    - master
  pull_request:
    branches:
    - main
    - master
env:
  CI: 'true'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NODE_ENV: test
  NODE_OPTIONS: --max-old-space-size=4096
  TS_NODE_PROJECT: tsconfig.json
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Cache build dependencies
      uses: actions/cache@v3
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
    - name: Run setup
      run: echo "Running setup"
    - name: Install dependencies
      run: echo "No install command specified for this language"
    - name: Build project
      run: echo "No build command specified for this language"
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Cache test dependencies
      uses: actions/cache@v3
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
    - name: Run unit-tests
      run: echo "Running unit-tests"
    needs:
    - build
