name: CI/CD Pipeline
'on':
  push:
    branches:
    - main
    - master
  pull_request:
    branches:
    - main
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up environment
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install dependencies
      run: npm install
    - name: Build project
      run: npm run build
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run unit tests
      run: npm test
    - name: Run integration tests
      run: npm run test:integration
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Build artifact
      run: npm run build:prod
    - name: Deploy
      run: echo "Deploy step - configure based on deployment target"
